# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - choo-pwa-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - choo-pwa-dependencies-

      - run: npm install

      # Update cache
      - save_cache:
          paths:
            - node_modules
          key: choo-pwa-dependencies-{{ checksum "package.json" }}

      # Run tests
      #- run: yarn test

      # Install AWS's CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y install python-dev
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      # Build the Docker container
      - run:
          name: Build the Docker container
          command: |
            docker build -t 711655675495.dkr.ecr.us-east-1.amazonaws.com/choo-pwa:latest .

      # Push the built containers to AWS ECR
      - run:
          name: Push the Docker container
          command: |
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            docker push 711655675495.dkr.ecr.us-east-1.amazonaws.com/choo-pwa:latest

      # Trigger a AWS ECS service update that will force the cluster to
      # re-pull the Docker container(s), to get the 'latest' tagged version
      - run:
          name: Trigger a ECS deploy
          command: |
            aws ecs update-service --region us-east-1 --cluster choo-pwa-cluster --service choo-pwa-service --force-new-deployment
